version: '3'

services:
  web:
    build: .
    command:
      #python music.py 
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sungjoon
      - POSTGRES_PASSWORD=148bvc
      - POSTGRES_DB=dethatbit_dev

  music:
    command:
      python music.py
volumes:
  postgres_data:
    