version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn DeThatBit.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
      
      
volumes:
  postgres_data:
  static_volume:
    